name: CI

on:
  push:
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read  # to fetch code (actions/checkout)

jobs:
  ci:
    strategy:
      # Allows for matrix sub-jobs to fail without canceling the rest
      fail-fast: false

      # MATRIX:
      # =======
      # Required parameters:
      #  os                  the os to run on
      #  python-version      the python version to use
      #  backend             the backend to use
      #  env                 any additional env variables. Set to '{}' for none
      # Optional parameters:
      #  allowed_failure     whether the job is allowed to fail
      #  extra_hash          extra hash str to differentiate from other caches with similar name (must always start with '-')
      matrix:
        # Tests [amd64]
        #
        os: [ubuntu-latest]
        env:
          - BOOLEAN: true
            ALWAYS: 'blah'
            SOMETIMES: 'bar'
          - BOOLEAN: false
            ALWAYS: 'blah'
        env2: [{ STYLE: 'flow', BOOLEAN: true, ALWAYS: 'blah' }]
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:
      - name: debug ${{ toJson(matrix.env) }}
        run: |
          echo '${{ toJson(matrix.env) }}'
          echo '${{ matrix.env }}'
          echo '${{ toJson(matrix.env.ALWAYS) }}'
          echo '${{ toJson(matrix.env.BOOLEAN) }}'
          echo '${{ toJson(matrix.env.SOMETIMES) }}'
          echo '${{ toJson(matrix.env2) }}'
          echo '${{ matrix.env2 }}'

      - name: ENV
        env: ${{ matrix.env }}
        run: env
      - name: iftest1
        if: matrix.env.BOOLEAN
        run: echo ''
      - name: iftest2
        if: ${{ matrix.env.BOOLEAN }}
        run: echo ''
      - name: iftest6
        if: ${{ matrix.env.BOOLEAN == 'true' }}
        run: echo ''
      - name: iftest7
        if: ${{ matrix.env.BOOLEAN == 'true' }}
        run: echo ''
      - name: if true
        if: true
        run: echo
      - name: if string true
        if: 'true'
        run: echo
      - name: if false
        if: false
        run: echo
      - name: if string false
        if: 'false'
        run: echo
      - name: if zero
        if: 0
        run: echo
      - name: if one
        if: 1
        run: echo
      - name: if string empty
        if: ''
        run: echo
      - name: if string zero
        if: '0'
        run: echo
      - name: if string one
        if: '1'
        run: echo
      - name: true eq 1
        if: ${{ true == 1 }}
        run: echo
      - name: 1 eq true
        if: ${{ 1 == true }}
        run: echo
      - name: string true eq 1
        if: ${{ 'true' == 1 }}
        run: echo
      - name: true eq string true
        if: ${{ true == 'true' }}
        run: echo
      - name: string true eq true
        if: ${{ 'true' == true }}
        run: echo
